#!/usr/bin/env python3
"""Generate _shared/ethics-appendix.jinja from the ethics registry.

The AGENTS.md appendix used to hard-wire the section include chain as one
hand-maintained Jinja line, and the same gate appeared a second time as a
hand-written predicate in tests/test_render_invariants.py — four places
(manifest intent, FLAGS vocabulary, include chain, test selector) stating
the same fact. The registry row's `gate` is now the single spelling: this
generator reads it and emits the chain, and the render-invariants predicate
evaluates the same string. Adding a section edits REGISTRY.yml once; this
file and the predicate both follow.

The emitted chain keeps the old hand-written shape: unconditional sections
first (they come first in registry order), then each gated include, with the
trailing `{%- ... %}` left-trim marker on the LAST entry so the rendered
guide still ends in exactly one newline (see AGENTS.md.jinja's comment).

Usage: python tools/gen_ethics_appendix.py [--check]

    --check   verify the committed file matches regeneration (drift gate)
"""

from __future__ import annotations

import sys
from pathlib import Path

TOP = Path(__file__).resolve().parent.parent
if str(TOP) not in sys.path:
    sys.path.insert(0, str(TOP))

from tools import ethics  # noqa: E402

OUTPUT = TOP / "_shared" / "ethics-appendix.jinja"

HEADER = (
    # A {#- -#} comment trims both its own newline and the include line's,
    # so the chain renders flush against AGENTS.md's preceding paragraph --
    # a bare {# #} would emit one blank line per header line.
    "{#- GENERATED by tools/gen_ethics_appendix.py -- do not edit; "
    "source: _shared/ethics/REGISTRY.yml (status + gate). Drift check: --check. -#}"
)


def render_chain() -> str:
    """The include chain for every section the registry marks active."""
    entries: list[str] = []
    for row in ethics.load_registry():
        if row.get("status") != "active":
            continue
        file = str(row["file"])
        gate = str(row.get("gate") or "").strip()
        if not gate or gate == "true":
            entries.append(f'{{% include "{file}" %}}')
        else:
            entries.append(f'{{% if {gate} %}}{{% include "{file}" %}}{{% endif %}}')
    if not entries:
        msg = "the registry has no active sections -- refusing to emit an empty appendix"
        raise SystemExit(msg)
    chain = "".join(entries)
    # The old hand-written chain right-trims its closing tag (endif -%}), so
    # the newline after the last include stays the appendix's only trailing
    # one. An unconditional tail would need the trim on the include instead.
    if chain.endswith("{% endif %}"):
        chain = chain[: -len("{% endif %}")] + "{% endif -%}"
    else:
        chain = chain[: -len("%}")] + "-%}"
    return HEADER + chain + "\n"


def main(argv: list[str] | None = None) -> int:
    argv = argv if argv is not None else sys.argv[1:]
    expected = render_chain()
    if "--check" in argv:
        actual = OUTPUT.read_text(encoding="utf-8") if OUTPUT.is_file() else ""
        if actual != expected:
            print(f"{OUTPUT} is stale; run: python tools/gen_ethics_appendix.py", file=sys.stderr)
            return 1
        print(f"{OUTPUT} matches the registry")
        return 0
    OUTPUT.write_text(expected, encoding="utf-8")
    print(f"wrote {OUTPUT} ({expected.count('include')} sections)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
