#!/usr/bin/env python3
"""MCP server exposing this template's own tooling to an agent.

`tools/batch.py`, `tools/detect.py` and `tools/questionnaire.py` are already
the machine-readable layer over this repository; this server is how an MCP
host (Claude Desktop, an IDE agent, the MCP Inspector) calls them instead of
shelling out and parsing text.

Run it over stdio (how an MCP host launches a server):

    uv run python tools/mcp_server.py

Or serve it over HTTP, for a host that connects to a URL:

    uv run python tools/mcp_server.py --transport streamable-http

Debug it with the MCP Inspector:

    uv run mcp dev tools/mcp_server.py

Binding to a non-local address (--host 0.0.0.0) requires MCP_ALLOWED_HOSTS:
the SDK arms its DNS-rebinding protection only while the server binds to
localhost, so a publicly bound server would accept any Host header without an
explicit allowlist. This server refuses to start in that state.

Two protocol facts shape the implementation:

- **stdout belongs to the protocol.** Copier prints progress to stdout, so
  every render here runs inside `batch.report_stream_only()` (fd 1 redirected
  to stderr). A stray print would corrupt the session.
- **Tools are the contract.** Each docstring below is what the model reads to
  decide when to call it, so they state the cost (rendering, installing,
  network) and what is returned.

None of these tools guess the questionnaire: the shape questions
(`project_type`, `include_*`, ...) stay the caller's decision, per
notes/SPEC-adoption.md section 12.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
import tempfile
from collections.abc import Sequence
from pathlib import Path
from typing import Any
from typing import Literal
from typing import cast

TOP = Path(__file__).resolve().parent.parent
if str(TOP) not in sys.path:
    sys.path.insert(0, str(TOP))

from mcp.server import MCPServer  # noqa: E402
from mcp.server.mcpserver.exceptions import ToolError  # noqa: E402
from mcp.server.transport_security import TransportSecuritySettings  # noqa: E402
from tools import adopt  # noqa: E402
from tools import batch  # noqa: E402
from tools import detect  # noqa: E402
from tools import questionnaire  # noqa: E402

GIT = batch.GIT
server = MCPServer("python-copier-template")

__all__ = ["main", "server"]


@server.tool()
def list_questions(*, asked_only: bool = True) -> dict[str, Any]:
    """List this template's questionnaire in ask order.

    Returns {"count", "questions"}; each entry has name, type, default (as written -- defaults are Jinja
    expressions), when, help, choices and source file. `internal` marks the
    derived `when: false` variables, which `asked_only=True` (the default)
    excludes. Call this before `render_project`: it is the only way to know
    which answers are valid and what each question defaults to. Two questions
    (`package_manager`, `oj_kind`) carry a `choices_template` instead of a
    resolved list, because their choices narrow themselves from earlier
    answers.
    """
    questions, _settings = questionnaire.load_questions()
    selected = [question.as_dict() for question in questions if not (asked_only and question.internal)]
    return {"count": len(selected), "questions": selected}


@server.tool()
def inspect_project(path: str, *, takeover: bool = False) -> dict[str, Any]:
    """Report what a project already has, and which operation fits it.

    Returns `mode` (fresh / adopt / update / foreign), the facts found on
    disk, the template outputs that would overwrite existing files
    (`collisions`), and `suggested_answers` for a copy or an adoption.

    Read `mode` before rendering anything: `update` means this project was
    already generated by this template (run `copier update`, not a copy),
    `foreign` means another template owns it and the call is refused unless
    `takeover=True`. Filesystem only -- no render, no network.
    """
    try:
        detection = detect.detect(Path(path).resolve(), takeover=takeover)
    except (detect.DetectError, OSError) as exc:
        raise ToolError(str(exc)) from exc
    return detection.as_dict()


@server.tool()
def template_status() -> dict[str, Any]:
    """Report this template checkout's own state.

    `latest_tag` and `head` come from git; `commits_behind_latest_tag` is the
    trap this repository lives with -- `copier copy` without `--vcs-ref`
    resolves the latest *tag*, which for a fork can point at a long-abandoned
    ancestor. `dirty` means uncommitted template changes are included in any
    render done from this checkout.
    """
    describe = batch.git(TOP, "describe", "--tags", "--abbrev=0").stdout.strip()
    head = batch.git(TOP, "rev-parse", "--short", "HEAD").stdout.strip()
    behind = batch.git(
        TOP, *(["rev-list", "--count", f"{describe}..HEAD"] if describe else ["--version"])
    ).stdout.strip()
    questions, settings = questionnaire.load_questions()
    return {
        "repo": str(TOP),
        "template_dir": str(detect.TEMPLATE_DIR),
        "questions": len(questions),
        "asked_questions": sum(1 for question in questions if not question.internal),
        "settings": sorted(settings),
        "latest_tag": describe or None,
        "head": head or None,
        "commits_behind_latest_tag": int(behind) if behind.isdigit() else None,
        "dirty": bool(batch.git(TOP, "status", "--porcelain").stdout.strip()),
    }


@server.tool()
def adopt_project(
    path: str,
    *,
    ref: str | None = None,
    answers: dict[str, Any] | None = None,
    dry_run: bool = True,
    merge_deps: bool = True,
) -> dict[str, Any]:
    """Adopt the template into an existing project, transactionally.

    `dry_run=True` (the default) only plans: nothing is written, and the
    result reports which existing files would be left alone (`skip`), which
    revision would be expanded (`ref`, `ref_reason`), what would be added, and
    which dependencies `deps` would add to the project's pyproject.toml. Call
    it first.

    `merge_deps` (default true) merges the dependencies the template would
    have generated into the adopter's pyproject.toml: only names it does not
    already declare are added, an existing pin is never rewritten (a
    difference is reported in `deps.differing`), and the rest of the file is
    left alone. Pass false to leave the file untouched.

    With `dry_run=False` the adoption is verified: if any existing file
    changed or disappeared -- a collision the plan did not cover -- the run is
    rolled back (originals restored, everything it created deleted) and
    `error` says why, so a failed adoption leaves the project exactly as it
    was. `ref` defaults to the latest tag *only* when that tag carries this
    questionnaire, otherwise the default branch; `answers` overrides what
    `inspect_project` derived. Files under `skip` are never written over, and
    everything the project does not have yet is still added.
    """
    if not Path(path).is_dir():
        msg = f"not a directory: {path}"
        raise ToolError(msg)
    try:
        with batch.report_stream_only():
            result = adopt.adopt(
                Path(path).resolve(),
                ref=ref,
                answers=answers or {},
                dry_run=dry_run,
                merge_deps=merge_deps,
            )
    except adopt.OwnershipError as exc:
        raise ToolError(str(exc)) from exc
    except (adopt.AdoptError, OSError) as exc:
        raise ToolError(str(exc)) from exc
    if not result.ok:
        msg = f"adoption failed and was rolled back: {result.error}"
        raise ToolError(msg)
    return result.as_dict()


@server.tool()
def render_project(answers: dict[str, Any], *, dest: str | None = None, prepare: bool = False) -> dict[str, Any]:
    """Render the template with `answers` and report what it produced.

    `answers` are the copier answers; unset questions fall back to their
    defaults (this is `--defaults`), so usually only `project_type` and the
    Project Details are needed. The render happens from this checkout, so
    uncommitted template changes are included -- run `inspect_project` first
    if the target may be an existing project.

    `dest` defaults to a fresh temporary directory. `prepare=True` also runs
    the project's install command (`uv sync` / `pixi install` / `poetry
    install`, chosen from what was rendered), which needs the network on a
    cold cache. Returns the destination path, the file count and the paths
    (relative) so a caller can read the files it needs.
    """
    work = Path(dest).resolve() if dest else Path(tempfile.mkdtemp(prefix="mcp-render-"))
    work.mkdir(parents=True, exist_ok=True)
    try:
        with batch.report_stream_only():
            batch.render(str(TOP), work, answers)
            checks = [batch.prepare_environment(work, "render")] if prepare else []
    except Exception as exc:  # noqa: BLE001  WHYNOT: the tool must report, not crash the session.
        msg = f"render failed: {type(exc).__name__}: {exc}"
        raise ToolError(msg) from exc
    failed = [check for check in checks if not check.ok]
    if failed:
        msg = f"render succeeded but prepare failed: {failed[0].detail}"
        raise ToolError(msg)
    files = sorted(str(path.relative_to(work)) for path in work.rglob("*") if path.is_file())
    return {
        "dest": str(work),
        "file_count": len(files),
        "files": files,
        "top_level": sorted({name.split("/")[0] for name in files}),
    }


@server.tool()
def list_batch_requests(jsonl: str) -> dict[str, Any]:
    """List the requests in a batch file (see docs/how-to/batch.md).

    Returns {"count", "requests"}: each request's id, note, destination and
    whether it carries an `update` phase, so a caller can pick one to run
    instead of running all of them. A malformed request list raises rather than returning a partial
    listing.
    """
    try:
        requests = batch.load_requests([Path(jsonl)])
    except (batch.SpecError, OSError) as exc:
        msg = f"cannot read {jsonl}: {exc}"
        raise ToolError(msg) from exc
    listed = [
        {
            "id": request.id,
            "note": request.note,
            "dest": request.dest,
            "has_update": request.update is not None,
            "checks": len(request.commands),
        }
        for request in requests
    ]
    return {"count": len(listed), "requests": listed}


@server.tool()
def run_batch(jsonl: str, *, only: str | None = None, prepare: bool = False, keep: bool = False) -> dict[str, Any]:
    """Run a batch of generation requests and return the verdict.

    `jsonl` is a request list (docs/how-to/batch.md); `only` is a regular
    expression selecting ids. Each line renders with the real template, runs
    its commands and judges its `expect` block, so this is the "did the
    change break a combination" check. `ok` is true only when every selected
    line passed; `lines[].checks[].detail` carries the observed value for a
    failure. Renders are real (uncommitted template changes included) and
    `prepare=True` additionally installs each project (network on a cold
    cache). `keep=True` leaves the rendered projects on disk and reports
    their directory.
    """
    try:
        requests = batch.load_requests([Path(jsonl)])
    except (batch.SpecError, OSError) as exc:
        msg = f"cannot read {jsonl}: {exc}"
        raise ToolError(msg) from exc
    if only:
        pattern = re.compile(only)
        requests = [request for request in requests if pattern.search(request.id)]
        if not requests:
            msg = f"no request id matches {only!r}"
            raise ToolError(msg)

    work = Path(tempfile.mkdtemp(prefix="mcp-batch-"))
    with batch.report_stream_only():
        results = [batch.run_request(request, work, TOP, prepare=prepare) for request in requests]
    return {
        "ok": all(result.ok for result in results),
        "work": str(work) if keep else None,
        "lines": [result.as_dict() for result in results],
    }


@server.resource("template://questionnaire")
def questionnaire_resource() -> str:
    """The full questionnaire as JSON, including the internal variables."""
    questions, settings = questionnaire.load_questions()
    return json.dumps({"questions": [q.as_dict() for q in questions], "settings": settings}, indent=2, default=str)


def _allowed_hosts() -> TransportSecuritySettings | None:
    """Turn MCP_ALLOWED_HOSTS / MCP_ALLOWED_ORIGINS into the SDK's settings."""
    raw_hosts = os.environ.get("MCP_ALLOWED_HOSTS")
    if not raw_hosts:
        return None
    hosts = [host.strip() for host in raw_hosts.split(",") if host.strip()]
    raw_origins = os.environ.get("MCP_ALLOWED_ORIGINS")
    if not raw_origins:
        return TransportSecuritySettings(allowed_hosts=hosts)
    origins = [origin.strip() for origin in raw_origins.split(",") if origin.strip()]
    return TransportSecuritySettings(allowed_hosts=hosts, allowed_origins=origins)


def main(args: Sequence[str] | None = None) -> None:
    """Run the MCP server with stdio (default) or Streamable HTTP."""
    parser = argparse.ArgumentParser(description="MCP server for python-copier-template")
    parser.add_argument("--transport", choices=["stdio", "streamable-http"], default="stdio")
    parser.add_argument("--host", default="127.0.0.1", help="Host to bind (streamable-http)")
    parser.add_argument("--port", type=int, default=8000, help="Port to bind (streamable-http)")
    parsed = parser.parse_args(args)
    transport = cast(Literal["stdio", "streamable-http"], parsed.transport)
    if transport == "streamable-http":
        host = cast(str, parsed.host)
        if host not in ("127.0.0.1", "localhost", "::1") and not os.environ.get("MCP_ALLOWED_HOSTS"):
            parser.error(
                "binding to a non-local host requires MCP_ALLOWED_HOSTS "
                "(comma-separated host allowlist) so the server does not "
                "accept every Host header"
            )
        server.run(transport=transport, host=host, port=cast(int, parsed.port), transport_security=_allowed_hosts())
    else:
        server.run(transport="stdio")


if __name__ == "__main__":
    main()
